// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwNi-Zrur9JW9UJBiF2iLSX_IZwT5sbGs',
    appId: '1:175661209191:web:c4c813dd3c86d3b610a6c2',
    messagingSenderId: '175661209191',
    projectId: 'cardswap-2722f',
    authDomain: 'cardswap-2722f.firebaseapp.com',
    storageBucket: 'cardswap-2722f.firebasestorage.app',
    measurementId: 'G-QWE70H29EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUR66QRzn0x-unFDRzIVTtMNHZg6OfDFY',
    appId: '1:175661209191:android:ebf75c7968d1833110a6c2',
    messagingSenderId: '175661209191',
    projectId: 'cardswap-2722f',
    storageBucket: 'cardswap-2722f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxpAK4kLeoyjSEjGBiApyA5qJD3EcNHuo',
    appId: '1:175661209191:ios:60f9f76bc10e0c0d10a6c2',
    messagingSenderId: '175661209191',
    projectId: 'cardswap-2722f',
    storageBucket: 'cardswap-2722f.firebasestorage.app',
    iosClientId: '175661209191-6lifmeisca6pu2ud51hk32pj95ghf5h5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxpAK4kLeoyjSEjGBiApyA5qJD3EcNHuo',
    appId: '1:175661209191:ios:60f9f76bc10e0c0d10a6c2',
    messagingSenderId: '175661209191',
    projectId: 'cardswap-2722f',
    storageBucket: 'cardswap-2722f.firebasestorage.app',
    iosClientId: '175661209191-6lifmeisca6pu2ud51hk32pj95ghf5h5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwNi-Zrur9JW9UJBiF2iLSX_IZwT5sbGs',
    appId: '1:175661209191:web:a041a1d4cd8aecc310a6c2',
    messagingSenderId: '175661209191',
    projectId: 'cardswap-2722f',
    authDomain: 'cardswap-2722f.firebaseapp.com',
    storageBucket: 'cardswap-2722f.firebasestorage.app',
    measurementId: 'G-HVJFKR437L',
  );
}
